from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtWidgets import QTextEdit, QScrollArea


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(953, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.params_layout = QtWidgets.QVBoxLayout()
        self.params_layout.setObjectName("params_layout")

        self.empty_label = QtWidgets.QLabel(self.centralwidget)
        self.empty_label.setObjectName("empty_label")
        self.empty_layout = QtWidgets.QVBoxLayout()
        self.empty_layout.setObjectName("empty_layout")
        self.empty_layout.addWidget(self.empty_label)

        self.settings_layout = QtWidgets.QGridLayout()
        self.settings_layout.setObjectName("settings_layout")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setObjectName("open_button")
        self.settings_layout.addWidget(self.open_button, 1, 0, 1, 1)
        self.get_file_label = QtWidgets.QLabel(self.centralwidget)
        self.get_file_label.setObjectName("get_file_label")
        self.settings_layout.addWidget(self.get_file_label, 0, 0, 1, 1)
        self.filename = QtWidgets.QLabel(self.centralwidget)
        self.filename.setObjectName("filename")
        self.settings_layout.addWidget(self.filename, 1, 1, 1, 1)

        self.params_layout.addLayout(self.settings_layout)

        self.preproc_layout = QtWidgets.QVBoxLayout()
        self.preproc_layout.setObjectName("preproc_layout")
        self.preproc_label = QtWidgets.QLabel(self.centralwidget)
        self.preproc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preproc_label.setObjectName("preproc_label")
        self.preproc_layout.addWidget(self.preproc_label)
        self.range_layout = QtWidgets.QGridLayout()
        self.range_layout.setObjectName("range_layout")
        self.from_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.from_lineEdit.setObjectName("from_lineEdit")
        self.range_layout.addWidget(self.from_lineEdit, 0, 1, 1, 1)
        self.from_label = QtWidgets.QLabel(self.centralwidget)
        self.from_label.setObjectName("from_label")
        self.range_layout.addWidget(self.from_label, 0, 0, 1, 1)
        self.to_label = QtWidgets.QLabel(self.centralwidget)
        self.to_label.setObjectName("to_label")
        self.range_layout.addWidget(self.to_label, 0, 2, 1, 1)
        self.to_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.to_lineEdit.setObjectName("to_lineEdit")
        self.range_layout.addWidget(self.to_lineEdit, 0, 3, 1, 1)
        self.preproc_layout.addLayout(self.range_layout)
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setObjectName("select_button")
        self.preproc_layout.addWidget(self.select_button)
        self.count_record_label = QtWidgets.QLabel(self.centralwidget)
        self.count_record_label.setObjectName("count_record_label")
        self.preproc_layout.addWidget(self.count_record_label)
        self.preproc_button = QtWidgets.QPushButton(self.centralwidget)
        self.preproc_button.setObjectName("preproc_button")
        self.preproc_layout.addWidget(self.preproc_button)
        self.params_layout.addLayout(self.preproc_layout)
        self.models_layout = QtWidgets.QVBoxLayout()
        self.models_layout.setObjectName("models_layout")
        self.model_label = QtWidgets.QLabel(self.centralwidget)
        self.model_label.setAlignment(QtCore.Qt.AlignCenter)
        self.model_label.setObjectName("model_label")
        self.models_layout.addWidget(self.model_label)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.model_rb_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_2.setObjectName("model_rb_2")
        self.gridLayout_6.addWidget(self.model_rb_2, 1, 0, 1, 1)
        self.model_rb_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_5.setObjectName("model_rb_5")
        self.gridLayout_6.addWidget(self.model_rb_5, 0, 2, 1, 1)
        self.model_rb_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_4.setObjectName("model_rb_4")
        self.gridLayout_6.addWidget(self.model_rb_4, 1, 1, 1, 1)
        self.model_rb_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_6.setObjectName("model_rb_6")
        self.gridLayout_6.addWidget(self.model_rb_6, 1, 2, 1, 1)
        self.model_rb_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_1.setObjectName("model_rb_1")
        self.gridLayout_6.addWidget(self.model_rb_1, 0, 0, 1, 1)
        self.model_rb_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_3.setObjectName("model_rb_3")
        self.gridLayout_6.addWidget(self.model_rb_3, 0, 1, 1, 1)
        self.model_rb_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_7.setObjectName("model_rb_7")
        self.gridLayout_6.addWidget(self.model_rb_7, 0, 3, 1, 1)
        self.model_rb_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.model_rb_8.setObjectName("model_rb_8")
        self.gridLayout_6.addWidget(self.model_rb_8, 1, 3, 1, 1)
        self.models_layout.addLayout(self.gridLayout_6)
        self.params_layout.addLayout(self.models_layout)
        self.params_layout.addLayout(self.empty_layout)

        self.main_layout.addLayout(self.params_layout)

        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")

        self.log_layout = QtWidgets.QVBoxLayout()
        self.log_layout.setObjectName("log_layout")

        plot_widget = QWebEngineView()
        plot_widget.setHtml("")

        self.log_text_edit = QTextEdit()
        self.log_text_edit.setReadOnly(True)
        self.scroll_area = QScrollArea()
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setWidget(self.log_text_edit)
        self.log_layout.addWidget(self.scroll_area)

        self.result_layout.addWidget(plot_widget)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.result_layout.addWidget(self.start_button)
        self.main_layout.addLayout(self.result_layout)
        self.main_layout.addLayout(self.log_layout)
        self.gridLayout.addLayout(self.main_layout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_log(self, log_message):
        self.log_text_edit.append(log_message)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anomaly Detection"))
        self.open_button.setText(_translate("MainWindow", "Открыть"))
        self.get_file_label.setText(_translate("MainWindow", "Выбрать файл с данными:"))
        self.filename.setText(_translate("MainWindow", "Название файла"))
        self.preproc_label.setText(_translate("MainWindow", "Диапазон"))
        self.from_lineEdit.setInputMask(_translate("MainWindow", "дд-мм-гггг"))
        self.from_label.setText(_translate("MainWindow", "от"))
        self.to_label.setText(_translate("MainWindow", "до"))
        self.to_lineEdit.setInputMask(_translate("MainWindow", "дд-мм-гггг"))
        self.select_button.setText(_translate("MainWindow", "Выбрать"))
        self.count_record_label.setText(_translate("MainWindow", "Количество записей:"))
        self.preproc_button.setText(_translate("MainWindow", "Предобработать"))
        self.model_label.setText(_translate("MainWindow", "Модель"))
        self.model_rb_2.setText(_translate("MainWindow", "LSTM"))
        self.model_rb_5.setText(_translate("MainWindow", "XGBoost"))
        self.model_rb_4.setText(_translate("MainWindow", "SARIMA"))
        self.model_rb_6.setText(_translate("MainWindow", "CatBoost"))
        self.model_rb_1.setText(_translate("MainWindow", "RNN"))
        self.model_rb_3.setText(_translate("MainWindow", "TadGAN"))
        self.model_rb_7.setText(_translate("MainWindow", "Isolation Forest"))
        self.model_rb_8.setText(_translate("MainWindow", "Holt-Winters"))
        self.start_button.setText(_translate("MainWindow", "Запустить"))
